### PR TITLE
Storage buckets

### PR DESCRIPTION
**Pull request by Siyabonga-Mbuyisa-u20491621**
Add Storage Functionality

### CODE REVIEW

**Review by Segadimane-Makau — APPROVED** [review]
Approved

**Review by Xerof47Vel — APPROVED** [review]

**Review by TshegofatsoMapheto — APPROVED** [review]
Approved

**Comment by tomosaHub** [comment]
Try creating .env file and store the Pool Id.

IDENTITY_POOL_ID=your_identity_pool_id
REGION=your_region
USER_POOL_ID=your_user_pool_id
USER_POOL_WEB_CLIENT_ID=your_user_pool_web_client_id

**Review by tomosaHub — COMMENTED** [review]
try add the .env file and store all the pool id there.

IDENTITY_POOL_ID=your_identity_pool_id
REGION=your_region
USER_POOL_ID=your_user_pool_id
USER_POOL_WEB_CLIENT_ID=your_user_pool_web_client_id

**Pull request closed without merging**
